"""
Daedalus: A Machine Learning library
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['DataFrame', 'ERROR', 'INFEASIBLE', 'KNN', 'LinearRegression', 'LogisticRegression', 'Matrix', 'Model', 'NeuralNetwork', 'OPTIMAL', 'OptimizationResult', 'SimplexSolver', 'SolutionStatus', 'StandardScaler', 'UNBOUNDED', 'accuracy_score', 'confusion_matrix', 'f1_score', 'mcc_score', 'mean_squared_error', 'precision_score', 'r2_score', 'read_csv', 'recall_score', 'train_test_split']
class DataFrame:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, col_name: str, col_data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | str]) -> None:
        """
        Constructs a DataFrame with an initial column.
        """
    def add_column(self, name: str, col_data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex | typing.SupportsInt | typing.SupportsIndex | str]) -> None:
        ...
    @typing.overload
    def at(self, row: typing.SupportsInt | typing.SupportsIndex, col_name: str) -> float | int | str:
        ...
    @typing.overload
    def at(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float | int | str:
        ...
    def drop_column(self, name: str) -> None:
        ...
    def encode_binary(self, column_name: str, val0: str = '', val1: str = '') -> None:
        ...
    def filter(self, col_name: str, predicate: collections.abc.Callable) -> DataFrame:
        """
        Filters rows using a Python lambda or function.
        """
    def get_column_names(self) -> list[str]:
        ...
    def head(self, n: typing.SupportsInt | typing.SupportsIndex = 5) -> DataFrame:
        """
        Returns the first n rows of the DataFrame.
        """
    def to_matrix(self, target_columns: collections.abc.Sequence[str]) -> Matrix:
        ...
    def to_string(self) -> str:
        ...
    @property
    def cols(self) -> int:
        ...
    @property
    def rows(self) -> int:
        ...
class KNN(Model):
    def __init__(self, k: typing.SupportsInt | typing.SupportsIndex = 3) -> None:
        ...
    def fit(self, X: Matrix, y: Matrix) -> None:
        ...
    def predict(self, X: Matrix) -> Matrix:
        ...
class LinearRegression(Model):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.01, reg_lambda: typing.SupportsFloat | typing.SupportsIndex = 0.01, penalty: str = 'none') -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix) -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix, epochs: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def load_model(self, filename: str) -> None:
        ...
    def predict(self, X: Matrix) -> Matrix:
        ...
    def save_model(self, filename: str) -> None:
        ...
class LogisticRegression(Model):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.01, reg_lambda: typing.SupportsFloat | typing.SupportsIndex = 0.01, penalty: str = 'none') -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix) -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix, epochs: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def load_model(self, filename: str) -> None:
        ...
    def predict(self, X: Matrix) -> Matrix:
        ...
    def predict_proba(self, X: Matrix) -> Matrix:
        ...
    def save_model(self, filename: str) -> None:
        ...
class Matrix:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def create_filled_matrix(rows: typing.SupportsInt | typing.SupportsIndex, cols: typing.SupportsInt | typing.SupportsIndex, fill_value: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def created_diagonal_scaler(rows: typing.SupportsInt | typing.SupportsIndex, cols: typing.SupportsInt | typing.SupportsIndex, value: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def created_diagonal_vector(rows: typing.SupportsInt | typing.SupportsIndex, cols: typing.SupportsInt | typing.SupportsIndex, values: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> Matrix:
        ...
    def LU(self) -> tuple[Matrix, Matrix, Matrix]:
        ...
    def QR(self) -> tuple[Matrix, Matrix]:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @typing.overload
    def __add__(self, arg0: Matrix) -> Matrix:
        ...
    def __buffer__(self, flags):
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
    def __call__(self, r: typing.SupportsInt | typing.SupportsIndex, c: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def __eq__(self, arg0: Matrix) -> bool:
        ...
    def __ge__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __getitem__(self, arg0: typing.Any) -> typing.Any:
        ...
    def __gt__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __iadd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def __isub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __itruediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __le__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __lt__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, arg0: Matrix) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __ne__(self, arg0: Matrix) -> bool:
        ...
    def __radd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __release_buffer__(self, buffer):
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __setitem__(self, arg0: tuple, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @typing.overload
    def __sub__(self, arg0: Matrix) -> Matrix:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def abs(self) -> Matrix:
        ...
    def add_scaled_row(self, src_idx: typing.SupportsInt | typing.SupportsIndex, dest_idx: typing.SupportsInt | typing.SupportsIndex, scalar: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def argmax(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def argmax_global(self) -> tuple[int, int]:
        ...
    def argmin(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def argmin_global(self) -> tuple[int, int]:
        ...
    def cholesky(self) -> Matrix:
        ...
    def contains(self, value: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def copy(self) -> Matrix:
        ...
    def det(self) -> float:
        ...
    def exp(self) -> Matrix:
        ...
    def get_col(self, idx: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def get_row(self, idx: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def inverse(self) -> Matrix:
        ...
    def log(self) -> Matrix:
        ...
    def mean(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def multiply_tiled(self, other: Matrix) -> Matrix:
        ...
    def norm(self, type: str = 'fro') -> float:
        ...
    def pinv(self, tol: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def power_to(self, power_value: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def rank(self) -> int:
        ...
    def reshape(self, new_rows: typing.SupportsInt | typing.SupportsIndex, new_cols: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def round(self, places: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def scale_row(self, row_idx: typing.SupportsInt | typing.SupportsIndex, scalar: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def set(self, r: typing.SupportsInt | typing.SupportsIndex, c: typing.SupportsInt | typing.SupportsIndex, val: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def set_col(self, idx: typing.SupportsInt | typing.SupportsIndex, new_col: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def set_row(self, idx: typing.SupportsInt | typing.SupportsIndex, new_row: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def sqrt(self) -> Matrix:
        ...
    def standard_deviation(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def sum(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def sum_all_elements(self) -> float:
        ...
    def svd(self) -> tuple[Matrix, Matrix, Matrix]:
        ...
    def swap_rows(self, r1: typing.SupportsInt | typing.SupportsIndex, r2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def to_string(self) -> str:
        ...
    def trace(self) -> float:
        ...
    def transpose(self) -> Matrix:
        ...
    def variance(self, axis: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    @property
    def cols(self) -> int:
        ...
    @property
    def rows(self) -> int:
        ...
class Model:
    def __init__(self) -> None:
        ...
    def fit(self, X: Matrix, y: Matrix) -> None:
        """
        Trains the model on the provided dataset.
        """
    def predict(self, X: Matrix) -> Matrix:
        """
        Makes predictions using the trained model parameters.
        """
class NeuralNetwork(Model):
    def __init__(self, lr: typing.SupportsFloat | typing.SupportsIndex = 0.01) -> None:
        ...
    def add(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix) -> None:
        ...
    @typing.overload
    def fit(self, X: Matrix, y: Matrix, epochs: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def predict(self, X: Matrix) -> Matrix:
        ...
class OptimizationResult:
    @property
    def objective_value(self) -> float:
        ...
    @property
    def status(self) -> SolutionStatus:
        ...
    @property
    def x(self) -> Matrix:
        ...
class SimplexSolver:
    def __init__(self) -> None:
        ...
    def solve(self, A: Matrix, b: Matrix, c: Matrix) -> OptimizationResult:
        """
        Solves LP: Maximize c*x subject to Ax <= b, x >= 0
        """
class SolutionStatus:
    """
    Members:
    
      OPTIMAL
    
      INFEASIBLE
    
      UNBOUNDED
    
      ERROR
    """
    ERROR: typing.ClassVar[SolutionStatus]  # value = <SolutionStatus.ERROR: 3>
    INFEASIBLE: typing.ClassVar[SolutionStatus]  # value = <SolutionStatus.INFEASIBLE: 1>
    OPTIMAL: typing.ClassVar[SolutionStatus]  # value = <SolutionStatus.OPTIMAL: 0>
    UNBOUNDED: typing.ClassVar[SolutionStatus]  # value = <SolutionStatus.UNBOUNDED: 2>
    __members__: typing.ClassVar[dict[str, SolutionStatus]]  # value = {'OPTIMAL': <SolutionStatus.OPTIMAL: 0>, 'INFEASIBLE': <SolutionStatus.INFEASIBLE: 1>, 'UNBOUNDED': <SolutionStatus.UNBOUNDED: 2>, 'ERROR': <SolutionStatus.ERROR: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class StandardScaler:
    def __init__(self) -> None:
        ...
    def fit(self, X: Matrix) -> None:
        ...
    def fit_transform(self, X: Matrix) -> Matrix:
        ...
    def get_is_fitted(self) -> bool:
        ...
    def get_means(self) -> list[float]:
        ...
    def get_std_devs(self) -> list[float]:
        ...
    def transform(self, X: Matrix) -> Matrix:
        ...
def accuracy_score(y_true: Matrix, y_pred: Matrix) -> float:
    ...
def confusion_matrix(y_true: Matrix, y_pred: Matrix) -> Matrix:
    ...
def f1_score(y_true: Matrix, y_pred: Matrix) -> float:
    ...
def mcc_score(y_true: Matrix, y_pred: Matrix) -> float:
    ...
def mean_squared_error(y_true: Matrix, y_pred: Matrix) -> float:
    """
    Calculates Mean Squared Error
    """
def precision_score(y_true: Matrix, y_pred: Matrix) -> float:
    ...
def r2_score(y_true: Matrix, y_pred: Matrix) -> float:
    """
    Calculates R-Squared Score
    """
def read_csv(filename: str, has_header: bool = True) -> DataFrame:
    ...
def recall_score(y_true: Matrix, y_pred: Matrix) -> float:
    ...
def train_test_split(X: Matrix, y: Matrix, test_size: typing.SupportsFloat | typing.SupportsIndex = 0.2, seed: typing.SupportsInt | typing.SupportsIndex = 42) -> tuple[Matrix, Matrix, Matrix, Matrix]:
    """
    Splits features and targets into training and testing sets.
    """
ERROR: SolutionStatus  # value = <SolutionStatus.ERROR: 3>
INFEASIBLE: SolutionStatus  # value = <SolutionStatus.INFEASIBLE: 1>
OPTIMAL: SolutionStatus  # value = <SolutionStatus.OPTIMAL: 0>
UNBOUNDED: SolutionStatus  # value = <SolutionStatus.UNBOUNDED: 2>
__version__: str = '0.1'
